# Generated by Django 5.0.4 on 2026-05-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_provider_email_provider_password_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='google_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_google_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='google_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_google_linked',
            field=models.BooleanField(default=False),
        ),
    ]
