# Generated by Django 5.0.4 on 2026-05-29 13:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_systemsetting_provider_is_apify_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='profile_photo',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='provider',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DiscountBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('discount_percent', models.IntegerField(default=0)),
                ('valid_until', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='api.provider')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('past_workplaces', models.JSONField(blank=True, default=list)),
                ('certifications', models.TextField(blank=True)),
                ('cert_image', models.CharField(blank=True, default='', max_length=500)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='api.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.booking')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceGig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('price_min', models.IntegerField(default=0)),
                ('price_max', models.IntegerField(default=0)),
                ('estimated_time', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='api.provider')),
            ],
        ),
    ]
