# Generated by Django 5.0.4 on 2026-06-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_provider_profile_photo_provider_years_of_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
